---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zhidong Zhang.
--- DateTime: 2025/5/20 23:23
---
-- 1.参数列表：优惠券id和用户id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

-- 2.数据key：库存key和订单key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
---- 判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足 返回1
    return 1
end
--判断用户是否下单
if(redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
-- 扣库存
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey,userId)
-- 发送消息到消息队列
redis.call('xadd', 'stream.orders', '*', 'userId',userId,'voucherId',voucherId,'id', orderId)

return 0




